# Generated by Django 3.2.9 on 2021-11-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(max_length=30)),
                ('right_bound', models.IntegerField(max_length=30)),
                ('left_bound', models.IntegerField(max_length=30)),
            ],
        ),
    ]
