# Generated by Django 3.2.9 on 2021-11-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('mass', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='potint',
            name='left_bound',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='potint',
            name='right_bound',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='potint',
            name='value',
            field=models.FloatField(),
        ),
    ]
