# Generated by Django 3.2.9 on 2021-11-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211112_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='wellvar',
            old_name='mass',
            new_name='rest_mass',
        ),
    ]
