# Generated by Django 3.2.9 on 2021-11-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211115_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='energies',
            name='Energy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='energies',
            name='n',
            field=models.IntegerField(default=0),
        ),
    ]
