# Generated by Django 3.2.9 on 2022-03-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211115_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticleSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrapLengh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='WellVar',
        ),
    ]
