# Generated by Django 3.2.9 on 2022-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_pfactors_xfactors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traplengh',
            name='length',
            field=models.FloatField(default=1e-10),
        ),
    ]
